server {
    listen 80;
    server_name api.fruitfulnetworkdevelopment.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
        default_type "text/plain";
    }

    # Everything else is intentionally inert for now
    location / {
        return 404;
    }
}
