  GNU nano 8.4                                                                          auth.fruitfulnetworkdevelopment.com.conf                                                                                   
server {
    server_name auth.fruitfulnetworkdevelopment.com;

    # Keycloak via localhost-only published port from Docker
    location / {
        proxy_pass http://127.0.0.1:8081;
        include /etc/nginx/sites-available/snippets/proxy_common.conf;

        # Keepalive / correctness
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/auth.fruitfulnetworkdevelopment.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/auth.fruitfulnetworkdevelopment.com/privkey.pem; # managed by Certbot
    include /etc/nginx/sites-available/snippets/ssl_params.conf; # managed by Certbot
}

server {
    listen 80;
    server_name auth.fruitfulnetworkdevelopment.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    return 301 https://$host$request_uri;
}
