server {
    server_name cuyahogaterravita.com www.cuyahogaterravita.com;

    root /srv/webapps/clients/cuyahogaterravita.com/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/fruitfulnetworkdevelopment.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fruitfulnetworkdevelopment.com/privkey.p>
    # Certbot created one certificate lineage stored at:
    # /etc/letsencrypt/live/fruitfulnetworkdevelopment.com/
    # That single certificate is cryptographically valid for all hostnames

    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    listen 80;
    server_name cuyahogaterravita.com www.cuyahogaterravita.com;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    return 301 https://$host$request_uri;
}
