"""Compatibility shim for tenant registry."""
from tenants.registry import (  # noqa: F401
    TENANTS_DIR,
    _validator_cache,
    TenantExistsError,
    TenantIdError,
    TenantIndexError,
    TenantNotFoundError,
    TenantRegistryError,
    TenantValidationError,
    create_tenant,
    delete_tenant,
    list_tenants,
    load_tenant,
    tenant_public_view,
    update_tenant,
    validate_return_to,
    validate_tenant_id,
)

__all__ = [
    "TENANTS_DIR",
    "_validator_cache",
    "TenantRegistryError",
    "TenantNotFoundError",
    "TenantValidationError",
    "TenantIndexError",
    "TenantExistsError",
    "TenantIdError",
    "validate_tenant_id",
    "list_tenants",
    "create_tenant",
    "update_tenant",
    "delete_tenant",
    "load_tenant",
    "validate_return_to",
    "tenant_public_view",
]
